import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('home dashboard uses compact spacing between and within cards', async () => {
  const homePage = await readFile(new URL('../app/pages/home.vue', import.meta.url), 'utf8')
  const gaugeNeedle = await readFile(new URL('../app/components/GaugeNeedle.vue', import.meta.url), 'utf8')
  const cumulativeChart = await readFile(new URL('../app/components/home/CumulativeSpendingChart.vue', import.meta.url), 'utf8')
  const radarChart = await readFile(new URL('../app/components/home/BudgetUsageRadarChart.vue', import.meta.url), 'utf8')

  assert.match(homePage, /grid grid-cols-2 gap-3 pb-20 pt-3/)
  assert.match(homePage, /body: 'p-3 sm:p-4'/)
  assert.equal(homePage.match(/:ui="compactCardUi"/g)?.length, 6)
  assert.match(homePage, /\{\{ periodLabel \}\}/)
  assert.match(homePage, /donutIncome\.value\.amount - totalExpenses\.value/)
  assert.match(homePage, /totalExpenses\.value \/ Math\.max\(donutIncome\.value\.amount, 1\)/)
  assert.match(homePage, />Total expenses and income<\/h3>/)
  assert.match(homePage, /grid grid-cols-3 gap-2 text-center/)
  assert.doesNotMatch(homePage, /expenseMoMChange/)
  assert.match(homePage, /categoryLabels: \['Expenses', 'Remaining'\]/)
  assert.match(homePage, /data: \[totalExpenses\.value, chartRemaining\.value\]/)
  assert.match(homePage, /cutout: '78%'/)
  assert.equal(homePage.match(/borderWidth: 0/g)?.length, 2)
  assert.match(homePage, /onClick: toggleDonutTooltip/)
  assert.match(homePage, /dataset\.categoryLabels\?\.\[item\.dataIndex\]/)
  assert.match(homePage, /<Doughnut class="relative z-20"/)
  assert.equal(homePage.match(/h-\[200px\] w-full max-w-sm/g)?.length, 2)
  assert.doesNotMatch(homePage, /lg:h-\[300px\]/)
  assert.match(gaugeNeedle, /bottom-\[22px\]/)
  assert.doesNotMatch(gaugeNeedle, /lg:bottom/)
  assert.match(cumulativeChart, /h-44 lg:h-\[215px\]/)
  assert.match(radarChart, /useBudgetIcon/)
  assert.match(radarChart, /icon: budget\.icon \?\? budgetIcon\(budget\.name\)/)
  assert.match(radarChart, /budgetPointPositionPlugin/)
  assert.match(radarChart, /afterDatasetsDraw\(chart: Chart<'radar'>\)/)
  assert.match(radarChart, /querySelectorAll<HTMLElement>\('\[data-budget-point-icon\]'\)/)
  assert.match(radarChart, /icon\.style\.left = `\$\{point\.x\}px`/)
  assert.match(radarChart, /icon\.style\.top = `\$\{point\.y\}px`/)
  assert.doesNotMatch(radarChart, /afterRender|requestAnimationFrame/)
  assert.match(radarChart, /:name="budget\.icon"/)
  assert.doesNotMatch(radarChart, /\{\{ budget\.name \}\}/)
  assert.match(radarChart, /layout: \{ padding: 20 \}/)
  assert.doesNotMatch(radarChart, /Number\(value\) === 100 \? ''/)
  assert.match(radarChart, /callback: \(value: string \| number\) => `\$\{value\}%`/)
  assert.match(radarChart, /borderColor: 'rgba\(245, 158, 11, 0\.45\)'/)
  assert.match(radarChart, /backgroundColor: 'rgba\(245, 158, 11, 0\.08\)'/)
  assert.match(radarChart, /pointRadius: 12/)
  assert.match(radarChart, /pointHoverRadius: 14/)
  assert.equal(radarChart.match(/topBudgets\.value\.map\(budget => `\$\{budget\.color\}99`\)/g)?.length, 2)
  assert.match(radarChart, /const budgetCount = ref\(5\)/)
  assert.match(radarChart, /MAX_CHART_BUDGETS = 10/)
  assert.match(radarChart, /fundedBudgets\.value\.slice\(0, budgetCount\.value\)/)
  assert.match(radarChart, /aria-label="Number of budgets shown"/)
  assert.match(radarChart, /\[writing-mode:vertical-lr\]/)
})
